version: '3.8'

services:
    todo_db:
      image: postgres:15-alpine
      container_name: todo_db
      restart: always
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: password
        POSTGRES_DB: todo_db
      volumes:
        -   postgres_data:/var/lib/postgresql/data
        -   ./migrations:/docker-entrypoint-initdb.d
      ports:
        - "5432:5432"

    notifier:
      build:
        context: ../notifier-service # путь к папке с нотификатором
      container_name: notifier_app
      restart: always
      ports:
        - "50051:50051"

    app:
      env_file:
        - .env
      build: .
      container_name: todo_app
      ports:
        - "8080:8080"           # Открывает "окно" в контейнер
      restart: always
      depends_on:
        - todo_db
        - notifier # Ждем запуска нотификатора
      environment:
        - DATABASE_URL=postgres://postgres:password@todo_db:5432/todo_db
        - NOTIFIER_ADDR=notifier:50051 

volumes:
  postgres_data: